apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hbn.fullname" . }}-config-data
  labels:
  {{- include "hbn.labels" . | nindent 4 }}
data:
  {{- if .Values.configuration.perDPUValuesYAML }}
  per_dpu_values.yaml: | {{ .Values.configuration.perDPUValuesYAML | nindent 4}}
  {{- end }}
  {{- if .Values.configuration.startupYAMLJ2 }}
  startup.yaml.j2: | {{ .Values.configuration.startupYAMLJ2 | nindent 4 }}
  {{- end }}
